services:
  
  elasticsearch:
    container_name: elk
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    ports:
      - 9200:9200
    volumes:
      - app_data:/var/lib/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node

    
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200

    
volumes:
  app_data:
